# LU Matrix Decomposition
**The LU Desomposition can be implemented using lu() function from scipy**

In [2]:
#Load libraries and dependencies
import numpy as np #library that support large, multi-dimensional arrays and matrice
from scipy.linalg import lu #library used for scientific computing and technical computing

In [4]:
#Define a 3x3 square matrix 
A=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
#LU Decomposition
P, L, U=lu(A)
print(P)
print(L)
print(U)

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
[[1.         0.         0.        ]
 [0.14285714 1.         0.        ]
 [0.57142857 0.5        1.        ]]
[[ 7.00000000e+00  8.00000000e+00  9.00000000e+00]
 [ 0.00000000e+00  8.57142857e-01  1.71428571e+00]
 [ 0.00000000e+00  0.00000000e+00 -1.58603289e-16]]


In [6]:
#Return the matrix to it original dimension values
B=P.dot(L).dot(U)
print(B)

[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


# QR Matrix Decomposition
**The QR Decomposition can be implemented using qr() function from scipy**

In [7]:
#import numpy as np #Library already imported
#Load the dependency for qr decomposition
from scipy.linalg import qr

In [8]:
#Define a 3x2 matrix
A=np.array([[1,2], [3,4], [5,6]])
print(A)

[[1 2]
 [3 4]
 [5 6]]


In [9]:
#QR Decomposition
Q, R=qr(A)
print(Q)
print(R)

[[-0.16903085  0.89708523  0.40824829]
 [-0.50709255  0.27602622 -0.81649658]
 [-0.84515425 -0.34503278  0.40824829]]
[[-5.91607978 -7.43735744]
 [ 0.          0.82807867]
 [ 0.          0.        ]]


In [10]:
#Return the matrix to original shape and values
B=Q.dot(R)
print(B)

[[1. 2.]
 [3. 4.]
 [5. 6.]]


# Cholesky Decomposition
**The Cholesky Decomposition can be implemented using cholesky() function from numpy**

In [19]:
#import numpy as np #Library already imported
#Load the dependency for cholesky decomposition
from numpy.linalg import cholesky

In [16]:
#Define a 3x3 square matrix
A=np.array([[2,1,1], [1,2,1], [1,1,2]])
print(A)

[[2 1 1]
 [1 2 1]
 [1 1 2]]


In [17]:
#Cholesky Decomposition
L=cholesky(A)
print(L)

[[1.41421356 0.         0.        ]
 [0.70710678 1.22474487 0.        ]
 [0.70710678 0.40824829 1.15470054]]


In [18]:
#Return the matrix to its original shape and value
B=L.dot(L.T)
print(B)

[[2. 1. 1.]
 [1. 2. 1.]
 [1. 1. 2.]]
